### ISSUE TITLE
Github API ext: 'create file block' cannot parse data:URL, makes corrupted files

### ISSUE THREAD

**Issue by baqirbeard** [Mistium/extensions.mistium#2]
Using the newly updated GitHub API extension, attempting to create a file using data:URL (or really anything else, like binary or hex or string, but that's irrelevant) in a repo will result in a corrupted file in such repo.

### **Steps to reproduce**

1. Import any type of file using the Files/Files Expanded ext as data:URL
![image](https://github.com/user-attachments/assets/3c79d022-7563-4f72-bf0f-3b17bb7d4962)

2. Use its data:URL to create a file of the same type and send it to your repo with GitHub API.
![image](https://github.com/user-attachments/assets/0284bbec-a379-4dd6-9256-53585d5a1d73)

3. GitHub cannot read it properly and downloading said file back results in corruption.

I've tested this with mp3 files, and downloading such song files from GitHub results in corruption and an inability to play the songs back.

**Comment by Mistium** [comment]
you have authenticated correctly?

**Comment by baqirbeard** [comment]
sorry i don't know what you mean
the auth token I made works, and from my testing this is what happens

**Comment by baqirbeard** [comment]
ok so the issues is fixed, we can close this issue now!
